### ISSUE TITLE
does it work in frontend when used with webpack/browserify

### ISSUE THREAD

**Issue by sagiavinash** [AndreasMadsen/trace#27]
does it work only in node envirnonment or is it universal?

**Comment by AndreasMadsen** [comment]
only node. The problem is that you need to be notified about every single async operation that happens in the program. In node we have created (work in progress) such a notification system, called [`async_wrap`](https://github.com/nodejs/tracing-wg/tree/master/docs/AsyncWrap), however this does not exists in the browser.

There is a very old issue about adding similar functionality to the browser: https://github.com/nodejs/tracing-wg/issues/9
